import type { SaveTarget } from './save.js';
import type { PageType } from './card-analysis.js';

/**
 * User settings and style profile types.
 * @see PRD §9.2
 */

export interface SkillToggles {
  contextualizer: boolean;
  tagger: boolean;
  styleMatcher: boolean;
  chronicle: boolean;
}

export type RetentionLevel = 'minimal' | 'standard' | 'detailed';

export interface UserSettings {
  defaultTemplate: string;
  defaultTarget: SaveTarget;
  outputLanguage: string;
  retentionLevel: RetentionLevel;
  enabledSkills: SkillToggles;
  /** Per-pageType default target overrides */
  targetOverrides?: Partial<Record<PageType, SaveTarget>>;
}

/**
 * Local user writing style profile, generated by StyleMatcher.
 * Stored locally, never uploaded.
 * @see PRD §6.3 StyleMatcher
 */
export interface UserStyleProfile {
  averageSentenceLength: number;
  preferredHeadingLevel: number;
  usesEmoji: boolean;
  usesQuoteBlocks: boolean;
  /** Common opening phrases */
  openingPatterns: string[];
  /** ISO 8601 timestamp when profile was last updated */
  updatedAt: string;
}
